import openseespy.opensees as ops

try:
    ops.wipe()
    ops.model('basic', '-ndm', 3, '-ndf', 6)
    ops.node(1, 0.0, 0.0, 0.0)
    ops.node(2, 1.0, 0.0, 0.0)
    ops.node(3, 0.0, 1.0, 0.0)
    ops.section('ElasticMembranePlateSection', 1, 25e9, 0.2, 0.2, 0.0)
    ops.element('ShellDKGT', 1, 1, 2, 3, 1)
    ops.fix(1, 1, 1, 1, 1, 1, 1)
    ops.fix(2, 1, 1, 1, 1, 1, 1)
    ops.fix(3, 1, 1, 1, 1, 1, 1)
    ops.timeSeries('Linear', 1)
    ops.pattern('Plain', 1, 1)
    ops.load(1, 0.0, 0.0, -100.0, 0.0, 0.0, 0.0)
    ops.constraints('Transformation')
    ops.numberer('RCM')
    ops.system('SparseGeneral')
    ops.algorithm('Linear')
    ops.integrator('LoadControl', 1.0)
    ops.analysis('Static')
    ok = ops.analyze(1)
    print('Analyze status:', ok)
    print('forces:', ops.eleResponse(1, 'forces'))
    print('stresses:', ops.eleResponse(1, 'stresses'))
    print('force:', ops.eleResponse(1, 'force'))
    print('section.force:', ops.eleResponse(1, 'section.force'))
except Exception as e:
    import traceback
    traceback.print_exc()
