import type { SlabPolygon, ColumnElement, ShearWallElement, PolylineWallElement, BeamElement, DropPanelElement, Point2D } from '../engine/types';

function esc(val: string): string {
  return `"${val.replace(/"/g, '""')}"`;
}

function fmt(val: number): string {
  return val.toFixed(6);
}

function frameSectionName(col: ColumnElement): string {
  return `C_${(col.width * 1000).toFixed(0)}x${(col.depth * 1000).toFixed(0)}`;
}

function beamSectionName(b: BeamElement): string {
  return `B_${(b.width * 1000).toFixed(0)}x${(b.depth * 1000).toFixed(0)}`;
}

function pierName(wall: ShearWallElement): string {
  return `W_${wall.id}`;
}

function polyPierName(wall: PolylineWallElement): string {
  return `PW_${wall.id}`;
}

function slabSectionName(slab: SlabPolygon): string {
  return `S_${(slab.thickness * 1000).toFixed(0)}mm`;
}

function storyHeight(elements: (ColumnElement | ShearWallElement | PolylineWallElement | BeamElement)[]): number {
  const heights = elements.map(e => 'height' in e ? (e as any).height : 3).filter((h: number) => h > 0);
  return heights.length > 0 ? heights[0] : 3;
}

export function exportE2K(
  slabs: SlabPolygon[],
  columns: ColumnElement[],
  walls: ShearWallElement[],
  polylineWalls: PolylineWallElement[],
  beams: BeamElement[],
  dropPanels: DropPanelElement[],
  concreteGrade: string,
  isCalibrated: boolean,
  pixelsPerMeter: number
): string {
  const lines: string[] = [];
  const nl = () => lines.push('');
  const table = (name: string, ...rows: Record<string, string>[]) => {
    if (rows.length === 0) return;
    lines.push(`TABLE: ${esc(name)}`);
    for (const row of rows) {
      for (const [k, v] of Object.entries(row)) {
        lines.push(`${k}=${v}`);
      }
    }
    nl();
  };

  const allElements: any[] = [...columns, ...walls, ...polylineWalls, ...beams];
  const storyH = storyHeight(allElements);

  nl();
  lines.push('########################################################################');
  lines.push('# ETABS E2K Export — Generated by RESLO');
  lines.push(`# Date: ${new Date().toISOString()}`);
  lines.push(`# Concrete Grade: ${concreteGrade}`);
  lines.push(`# Calibrated: ${isCalibrated}`);
  lines.push('########################################################################');
  nl();

  // PROJECT INFORMATION
  table('PROJECT INFORMATION', {
    'ProjectName': esc('RESLO — Structural Layout'),
    'FileDate': esc(new Date().toISOString()),
    'ProgramName': esc('RESLO Web App'),
  });

  // GRID DATA
  const gridLines: Record<string, string>[] = [];
  const allPts: Point2D[] = [];
  for (const s of slabs) for (const v of s.vertices) allPts.push(v);
  for (const c of columns) allPts.push(c.position);
  for (const w of walls) { allPts.push(w.startPoint); allPts.push(w.endPoint); }
  for (const pw of polylineWalls) for (const v of pw.vertices) allPts.push(v);
  for (const b of beams) { allPts.push(b.startPoint); allPts.push(b.endPoint); }
  for (const dp of dropPanels) for (const v of dp.vertices) allPts.push(v);

  if (allPts.length > 0) {
    let minX = allPts[0].x, maxX = allPts[0].x, minY = allPts[0].y, maxY = allPts[0].y;
    for (const p of allPts) {
      if (p.x < minX) minX = p.x; if (p.x > maxX) maxX = p.x;
      if (p.y < minY) minY = p.y; if (p.y > maxY) maxY = p.y;
    }
    const pad = Math.max((maxX - minX) * 0.2, 2);
    const gridSpacing = Math.pow(10, Math.floor(Math.log10(Math.max(maxX - minX, maxY - minY) / 5)));

    gridLines.push({ 'GridID': esc('X1'), 'X': fmt(minX - pad), 'Y': fmt(minY - pad), 'GridLineType': esc('Primary') });
    gridLines.push({ 'GridID': esc('X' + Math.ceil((maxX + pad - minX + pad) / gridSpacing + 1).toString()), 'X': fmt(maxX + pad), 'Y': fmt(maxY + pad), 'GridLineType': esc('Primary') });
    gridLines.push({ 'GridID': esc('Y1'), 'X': fmt(minX - pad), 'Y': fmt(minY - pad), 'GridLineType': esc('Primary') });
    gridLines.push({ 'GridID': esc('Y' + Math.ceil((maxY + pad - minY + pad) / gridSpacing + 1).toString()), 'X': fmt(maxX + pad), 'Y': fmt(maxY + pad), 'GridLineType': esc('Primary') });
  }
  if (gridLines.length > 0) table('GRID DATA', ...gridLines);

  // STORY DATA
  table('STORY DATA', {
    'Story': esc('STORY1'),
    'Height': fmt(storyH),
    'IsMasterStory': 'Yes',
  });

  // MATERIAL PROPERTIES
  const fck = parseInt(concreteGrade.replace('M', '')) || 25;
  const E = 5000 * Math.sqrt(fck) * 1000; // kN/m²
  table('MATERIAL PROPERTIES', {
    'Material': esc(`CONC_${concreteGrade}`),
    'Type': esc('Concrete'),
    'E': fmt(E),
    'Poisson': '0.2',
    'WeightPerUnitVolume': '25',
  });

  // FRAME SECTION PROPERTIES — columns
  const colSections = new Set<string>();
  for (const col of columns) {
    const name = frameSectionName(col);
    if (!colSections.has(name)) {
      colSections.add(name);
      table('FRAME SECTION PROPERTIES', {
        'Section': esc(name),
        'Material': esc(`CONC_${concreteGrade}`),
        'Shape': esc('Rectangular'),
        'Width': fmt(col.width),
        'Depth': fmt(col.depth),
      });
    }
  }

  // FRAME SECTION PROPERTIES — beams
  const beamSections = new Set<string>();
  for (const b of beams) {
    const name = beamSectionName(b);
    if (!beamSections.has(name)) {
      beamSections.add(name);
      table('FRAME SECTION PROPERTIES', {
        'Section': esc(name),
        'Material': esc(`CONC_${concreteGrade}`),
        'Shape': esc('Rectangular'),
        'Width': fmt(b.width),
        'Depth': fmt(b.depth),
      });
    }
  }

  // FRAME OBJECT ASSIGNMENTS — columns
  for (let i = 0; i < columns.length; i++) {
    const col = columns[i];
    const colLabel = `C${String(i + 1).padStart(3, '0')}`;
    table('FRAME OBJECT ASSIGNMENTS', {
      'Story': esc('STORY1'),
      'Column': esc(colLabel),
      'Point1': `${fmt(col.position.x)}, ${fmt(col.position.y)}, 0`,
      'Point2': `${fmt(col.position.x)}, ${fmt(col.position.y)}, ${fmt(col.height)}`,
      'Property': esc(frameSectionName(col)),
      'Angle': fmt(col.rotation * 180 / Math.PI),
      'CardinalPoint': '5',
    });
  }

  // FRAME OBJECT ASSIGNMENTS — beams
  for (let i = 0; i < beams.length; i++) {
    const b = beams[i];
    const beamLabel = `B${String(i + 1).padStart(3, '0')}`;
    table('FRAME OBJECT ASSIGNMENTS', {
      'Story': esc('STORY1'),
      'Beam': esc(beamLabel),
      'Point1': `${fmt(b.startPoint.x)}, ${fmt(b.startPoint.y)}, ${fmt(b.height)}`,
      'Point2': `${fmt(b.endPoint.x)}, ${fmt(b.endPoint.y)}, ${fmt(b.height)}`,
      'Property': esc(beamSectionName(b)),
      'CardinalPoint': '5',
    });
  }

  // SHELL PROPERTIES — slabs
  const slabSections = new Set<string>();
  for (const slab of slabs) {
    const name = slabSectionName(slab);
    if (!slabSections.has(name)) {
      slabSections.add(name);
      table('SHELL PROPERTIES', {
        'Section': esc(name),
        'Material': esc(`CONC_${concreteGrade}`),
        'Type': esc('Slab'),
        'Thickness': fmt(slab.thickness),
        'BendingThickness': fmt(slab.thickness),
      });
    }
  }

  // SHELL OBJECT ASSIGNMENTS — slabs
  for (const slab of slabs) {
    const vertStr = slab.vertices.map(v => `${fmt(v.x)}, ${fmt(v.y)}, 0`).join('; ');
    table('SHELL OBJECT ASSIGNMENTS', {
      'Story': esc('STORY1'),
      'Slab': esc(slab.id),
      'Property': esc(slabSectionName(slab)),
      'Vertices': esc(vertStr),
    });
  }

  // SHELL PROPERTIES — drop panels
  const dpSections = new Set<string>();
  for (const dp of dropPanels) {
    const name = `DP_${(dp.drop * 1000).toFixed(0)}mm`;
    if (!dpSections.has(name)) {
      dpSections.add(name);
      table('SHELL PROPERTIES', {
        'Section': esc(name),
        'Material': esc(`CONC_${concreteGrade}`),
        'Type': esc('Slab'),
        'Thickness': fmt(dp.drop),
        'BendingThickness': fmt(dp.drop),
      });
    }
  }

  // SHELL OBJECT ASSIGNMENTS — drop panels
  for (const dp of dropPanels) {
    if (dp.vertices.length >= 3) {
      const vertStr = dp.vertices.map(v => `${fmt(v.x)}, ${fmt(v.y)}, 0`).join('; ');
      table('SHELL OBJECT ASSIGNMENTS', {
        'Story': esc('STORY1'),
        'Slab': esc(dp.id),
        'Property': esc(`DP_${(dp.drop * 1000).toFixed(0)}mm`),
        'Vertices': esc(vertStr),
      });
    }
  }

  // PIER PROPERTIES — walls
  const wallPierSet = new Set<string>();
  for (const w of walls) {
    const pname = pierName(w);
    if (!wallPierSet.has(pname)) {
      wallPierSet.add(pname);
      table('PIER PROPERTIES', {
        'Pier': esc(pname),
        'Material': esc(`CONC_${concreteGrade}`),
        'Thickness': fmt(w.thickness),
      });
    }
  }
  for (const w of polylineWalls) {
    const pname = polyPierName(w);
    if (!wallPierSet.has(pname)) {
      wallPierSet.add(pname);
      table('PIER PROPERTIES', {
        'Pier': esc(pname),
        'Material': esc(`CONC_${concreteGrade}`),
        'Thickness': fmt(w.thickness),
      });
    }
  }

  // PIER OBJECT ASSIGNMENTS — walls (as area objects)
  for (const w of walls) {
    const dx = w.endPoint.x - w.startPoint.x;
    const dy = w.endPoint.y - w.startPoint.y;
    const len = Math.sqrt(dx * dx + dy * dy);
    if (len < 1e-10) continue;
    const ux = dx / len, uy = dy / len;
    const hw = w.thickness / 2;
    const px = -uy * hw, py = ux * hw;
    const verts = [
      { x: w.startPoint.x + px, y: w.startPoint.y + py },
      { x: w.endPoint.x + px, y: w.endPoint.y + py },
      { x: w.endPoint.x - px, y: w.endPoint.y - py },
      { x: w.startPoint.x - px, y: w.startPoint.y - py },
    ];
    const vertStr = verts.map(v => `${fmt(v.x)}, ${fmt(v.y)}, 0`).join('; ');
    table('PIER OBJECT ASSIGNMENTS', {
      'Story': esc('STORY1'),
      'Pier': esc(pierName(w)),
      'Vertices': esc(vertStr),
    });
  }

  // Polyline walls as pier area objects
  for (const pw of polylineWalls) {
    const allSegVerts: Point2D[] = [];
    for (let i = 0; i < pw.vertices.length - 1; i++) {
      const a = pw.vertices[i];
      const b = pw.vertices[i + 1];
      const dx = b.x - a.x, dy = b.y - a.y;
      const len = Math.sqrt(dx * dx + dy * dy);
      if (len < 1e-10) continue;
      const ux = dx / len, uy = dy / len;
      const hw = pw.thickness / 2;
      const px = -uy * hw, py = ux * hw;
      allSegVerts.push({ x: a.x + px, y: a.y + py });
    }
    // Close the polyline
    if (allSegVerts.length >= 3) {
      // Add the other side in reverse
      for (let i = pw.vertices.length - 1; i >= 0; i--) {
        const a = pw.vertices[i];
        const b = pw.vertices[Math.min(i + 1, pw.vertices.length - 1)];
        const dx = b.x - a.x, dy = b.y - a.y;
        const len = Math.sqrt(dx * dx + dy * dy);
        if (len < 1e-10) continue;
        const ux = dx / len, uy = dy / len;
        const hw = pw.thickness / 2;
        const px = -uy * hw, py = ux * hw;
        allSegVerts.push({ x: a.x - px, y: a.y - py });
      }
    }
    if (allSegVerts.length >= 3) {
      const vertStr = allSegVerts.map(v => `${fmt(v.x)}, ${fmt(v.y)}, 0`).join('; ');
      table('PIER OBJECT ASSIGNMENTS', {
        'Story': esc('STORY1'),
        'Pier': esc(polyPierName(pw)),
        'Vertices': esc(vertStr),
      });
    }
  }

  // LOAD CASE DATA
  table('LOAD CASE DATA', {
    'LoadCase': esc('DEAD'),
    'Type': esc('DEAD'),
  });
  table('LOAD CASE DATA', {
    'LoadCase': esc('LIVE'),
    'Type': esc('LIVE'),
  });

  // LOAD PATTERN DATA
  table('LOAD PATTERN DATA', {
    'LoadPat': esc('DEAD'),
    'Type': esc('DEAD'),
    'WeightMultiplier': '1',
  });
  table('LOAD PATTERN DATA', {
    'LoadPat': esc('LIVE'),
    'Type': esc('LIVE'),
    'WeightMultiplier': '0',
  });

  return lines.join('\n');
}
